name: Swift MacOS - Build and Run tests

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
          xcodebuild clean test -project AirConnect.xcodeproj -scheme AirConnect -destination 'platform=OS X,arch=x86_64' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        
