name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Swift
      uses: actions/setup-swift@v2
      with:
        swift-version: '5.5'

    - name: Build and Test
      run: |
        swift test --package-path Path/To/ClamTests
