name: XCUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run XCUnit Tests
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: List iOS Devices & Platforms
      run: |
        xcrun simctl list
        
    - name: Install iOS 14.2 Runtime
      run: |
        gem install xcode-install
        xcversion simulators --install='iOS 14.2'
        
    - name: Build and test
      run: |
        xcodebuild clean test -project Clam.xcodeproj -scheme Clam -destination 'platform=iOS Simulator,name=iPhone 12,OS=16.2'

    # You might want to include steps for reporting test results or artifacts
