name: Xcode Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ios:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Switch Xcode version
      run: sudo xcode-select -s "/Applications/Xcode_13.4.1.app"

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Create iPhone 8 Simulator
      run: xcrun simctl create "iPhone 8" "com.apple.CoreSimulator.SimDeviceType.iPhone-8" "com.apple.CoreSimulator.SimRuntime.iOS-14-4"

    - name: Xcode test on iPhone 8
      run: xcodebuild clean test -scheme "Clam" -destination 'platform=iOS Simulator,name=iPhone 8 (1st generation)'
