name: Run Unit Tests

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      # Check Xcode version (optional)
      - name: Check Xcode Version (Optional)
        run: |
          xcodebuild -version
        
      - name: Build and Test with Xcode
        run: |
          xcodebuild build -project Clam.xcodeproj -scheme ClamTests -destination 'platform=iOS Simulator,OS=14.1,name=iPad Pro (12.9-inch) (4th generation)' | xcpretty -s -only-testing:ClamTests/ValidatorTests/testValidEmail

        env:
          # Optional: Set Xcode version requirement here (e.g., Xcode-13.2)
          XCODE_VERSION: ${{ matrix.xcode }}


