name: Xcode Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ios:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Linter
      run: swiftlint

    - name: Switch Xcode version
      run: sudo xcode-select -s "/Applications/Xcode_13.4.1.app"

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Create iPhone SE Simulator
      run: xcrun simctl create "iPhone SE (1st generation)" "iPhone SE (1st generation)"

    - name: Xcode test on iPhone SE
      run: xcodebuild clean test -scheme "Clam" -destination 'platform=iOS Simulator,name=iPhone SE (1st generation)'
