name: Run Swift Tests

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: swift package update

      - name: Build and Test
        run: xcodebuild build-test -scheme Clam
