name: Run Unit Tests

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      # Check Xcode version (optional)
      - name: Check Xcode Version (Optional)
        run: |
          xcodebuild -version
          
      - name: Clean Build Folder (Optional)
        run: |
          xcodebuild clean -scheme ClamTests
        shell: bash
        
      - name: Build and Test with Xcode
        run: |
          xcodebuild test -scheme ClamTests -destination 'platform:iOS Simulator,name:iPhone 17.4 Simulator'
        env:
          # Optional: Set Xcode version requirement here (e.g., Xcode-13.2)
          XCODE_VERSION: ${{ matrix.xcode }}
