name: Swift Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install Xcode command line tools
        run: sudo xcode-select --install
      
      - name: Accept Xcode license
        run: sudo xcodebuild -license accept
      
      - name: Build and Test
        run: xcodebuild -project Clam.xcodeproj -scheme Clam -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 13' test
