name: Run Unit Tests

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: swift package update

      - name: Build and Test with Xcode
        uses: xcodeact/xcode-action@v1
        with:
          project: Clam.xcodeproj
          scheme: Clam
          test: true
          configuration: Release

