name: Run Unit Tests

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and Test with Xcode
        run: xcodebuild build-test -scheme Clam
