name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build project
      run: |
        xcodebuild build -scheme "ClamTests" -allowProvisioningUpdates

    - name: Run unit tests
      run: |
        xcodebuild test -scheme "ClamTests" -destination 'platform=iOS Simulator,name=iPhone 11' | xcpretty -s

    - name: Upload test results (optional)
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: TestResults
        path: ./path/to/test/reports
