name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, feature/* ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          xcodebuild test -project Clam.xcodeproj/ -scheme Clam -resultBundlePath TestResults -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 8"
